{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.serviceAccount.name }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Values.serviceAccount.namespace }}-app-role"
  namespace: "{{ .Values.serviceAccount.namespace }}"
rules:
- apiGroups: [""]
  resources: ["pods", "services", "persistentvolumeclaims", "secrets", "configmaps"]
  verbs: ["create", "get", "update", "delete", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Values.serviceAccount.namespace }}-app-role-binding"
  namespace: "{{ .Values.serviceAccount.namespace }}"
roleRef:
  kind: Role
  name: "{{ .Values.serviceAccount.namespace }}-app-role"
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: "{{ .Values.serviceAccount.name }}"
  namespace: "{{ .Values.serviceAccount.namespace }}"
{{- end }}
