application:
  name: ""
  namespace: ""
  version: "1.0.0"

keyVault:
  name: ""
  kvCsiClientId: ""
  tenantId: ""
  secrets:
    key1: ""
    key2: ""
    key3: ""
    key4: ""
    key5: ""
    key6: ""
    key7: ""
    key8: ""
    key9: ""
    key10: ""
    key11: ""
    key12: ""
    key13: ""
    key14: ""
    key15: ""
    key16: ""
    key17: ""
    key18: ""
    key19: ""
    key20: ""
    key21: ""
    key22: ""
    key23: ""
    key24: ""
    key25: ""
    key26: ""
    key27: ""
    key28: ""
    key29: ""
    key30: ""
    key31: ""
    key32: ""
    key33: ""
    key34: ""
    key35: ""

k8secret:
  name: ""
  providerClassName: ""




