name: ❓ Question
description: Ask a question or get clarification
title: '[Question]: '
labels: [question]
body:
  - type: textarea
    id: question
    attributes:
      label: Ask your question
      description: Be as specific as possible.
    validations:
      required: true

  - type: dropdown
    id: app
    attributes:
      label: Application
      options:
        - CMS
        - eCommerce
        - General
