apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Values.secret.providerClassName }}"
  namespace: "{{ .Values.application.namespace }}"
spec:
  provider: azure
  secretObjects:
  - secretName: "{{ .Values.secret.name }}"
    type: Opaque
    data:
    - objectName: "{{ .Values.storageAccount.keyVaultSecretNameForStorageAccountName }}"
      key: "azurestorageaccountname"
    - objectName: "{{ .Values.storageAccount.keyVaultSecretNameForStorageAccountAccessKey }}"
      key: "azurestorageaccountkey"
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.aks.kvCsiClientId }}"
    keyvaultName: "{{ .Values.storageAccount.keyVaultName }}"
    objects: |
      array:
        - |
          objectName: "{{ .Values.storageAccount.keyVaultSecretNameForStorageAccountName }}"
          objectType: secret
        - |
          objectName: "{{ .Values.storageAccount.keyVaultSecretNameForStorageAccountAccessKey }}"
          objectType: secret
    tenantId: "{{ .Values.aks.tenantId }}"
