apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.ingress.tlsSecretName }}
  namespace: {{ .Values.ingress.tlsSecretNamespace }}
spec:
  provider: azure
  secretObjects:
  - secretName: {{ .Values.ingress.tlsSecretName }}
    type: kubernetes.io/tls
    data:
    - objectName: "{{ .Values.ingress.certificateInKeyVault }}"
      key: tls.key
    - objectName: "{{ .Values.ingress.certificateInKeyVault }}"
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.ingress.secretProviderIdentity }}"
    keyvaultName: "{{ .Values.ingress.secretKeyVaultName }}"
    objects: |
      array:
        - |
          objectName: {{ .Values.ingress.certificateInKeyVault }}
          objectType: secret
    tenantId: {{ .Values.ingress.tenantId }}
    