
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.ingress.tlsSecretName }}-fallback"
  namespace: {{ .Values.ingress.tlsSecretNamespace }}   
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: "{{ .Values.ingress.tlsSecretName }}-loader"
---
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: "{{ .Values.ingress.tlsSecretName }}-loader"
#   namespace: {{ .Values.ingress.tlsSecretNamespace }}   
# spec:
#   type: ClusterIP
#   ports:
#   - port: 80
#     targetPort: 8080
#   selector:
#     app: "{{ .Values.ingress.tlsSecretName }}-loader"

