apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Values.ingress.tlsSecretName }}-loader-client"
  namespace: ingress
spec:
  hostAliases:
    - ip: "10.240.20.42"
      hostnames:
        - "ingresstest.com"
  containers:
    - name: "{{ .Values.ingress.tlsSecretName }}-loader-client"
      image: "{{ .Values.ingress.secretLoaderImageRepository }}/onecloud-health-probe:v1.1"
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
      - containerPort: 8080
      command: ["/bin/bash", "-c"]
      args:
        - export BACKEND_URL="http://ingresstest.com/ingress/";
          while true; do
            echo -e "\n Attemping $BACKEND_URL  \n";
            curl -sS "$BACKEND_URL";
            echo -e "\n ---------------------------- \n";
            sleep 60m;
          done;